apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: francofazzito/desafiokubernetes:latest
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_DB_URI
          value: "mongodb://mongo:mongo123@mongodb-service:27017"
        - name: MONGO_DB_NAME
          value: "test"
        - name: MONGO_DB_USER
          value: "mongo"
        - name: MONGO_DB_PASS
          value: "mongo123"
